### ISSUE TITLE
Dedicated directory for componentized implementation of Tic-Tac-Toe using vanilla JS

### ISSUE THREAD

**Issue by rasik210** [maurya777/react-training#1]
Hi Satish

I can see that all the files for the most basic implementation of Tic-Tac-Toe game is present inside a directory named "tictactoe-simple". Later you have improvised the basic solution by creating individual components as per their responsibility to make them reusable. But all the related files of the improvised solution e.g. board.js is present in the root of the repository itself. So it is hard to make out exact list of files I need to run the second implementation. I  request you to please keep all the related files of the improvised solution in a dedicated directory e.g. "tictactoe-componentized" or "tictactoe-improvised".

**Comment by maurya777** [comment]
Thanks for the feedback @rasik210 !

It needs an improved directory structure, which should fix it. I have started on work on it.

**Comment by maurya777** [comment]
Fixed in the latest commit
